-- Create notifications table to store push subscriptions
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription jsonb NOT NULL,
  created_at timestamptz DEFAULT now()
);
